name: Miles Van Denburg
title: Miles Van Denburg Github Website
logo: "/images/0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/miles-van-denburg-14068597?trk=nav_responsive_tab_profile_pic">View My LinkedIn Profile</a>
  <br>
  <a href="milesvandenburg.weebly.com">View My Portfolio</a>
  <br>
  <a href="https://github.com/MVanDenburg92">github.com/MVanDenburg92</a><br>

theme: jekyll-theme-minimal
