name: Miles Van Denburg
title: Miles Van Denburg Github Website
logo: "/images/0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a GIS analyst with a mind for creative innovation and implementation.
  During the outbreak of COVID-19, I managed a full load of graduate courses,
  while working as a course assistant converting the class to an online format in tandem with the course professor.
  As I head into the final year of my Masters in GIS at Clark University 
  I'm working for Clark Labs as a Remote Sensing Research Assistant 
  as part of the Half-Earth project with ESRI with the goal of creating
  a predictive climate change model for each country in the world for the year 2050.
  <a href="https://www.linkedin.com/in/miles-van-denburg-14068597?trk=nav_responsive_tab_profile_pic">View My LinkedIn Profile</a><br>
  <br>
  <a href="milesvandenburg.weebly.com">View My Portfolio</a>
  <br>
theme: jekyll-theme-minimal
